const types = {
  // actions fetching topics
  START_TO_GET_TOPICS: 'START_TO_GET_TOPICS',

  ERROR_TO_GET_TOPICS: 'ERROR_TO_GET_TOPICS',

  // actions fetching posts
  START_TO_GET_POSTS: 'START_TO_GET_POSTS',

  ERROR_TO_GET_POSTS: 'ERROR_TO_GET_POSTS',

  // actions on index page
  GET_TOPICS_FOR_INDEX_PAGE: 'GET_TOPICS_FOR_INDEX_PAGE',

  GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE: 'GET_PHOTOGRAPHY_POSTS_FOR_INDEX_PAGE',

  GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE: 'GET_INFOGRAPHIC_POSTS_FOR_INDEX_PAGE',

  GET_LATEST_POSTS_FOR_INDEX_PAGE: 'GET_LATEST_POSTS_FOR_INDEX_PAGE',

  GET_EDITOR_PICKS_FOR_INDEX_PAGE: 'GET_EDITOR_PICKS_FOR_INDEX_PAGE',

  GET_LATEST_TOPIC_FOR_INDEX_PAGE: 'GET_LATEST_TOPIC_FOR_INDEX_PAGE',

  GET_REVIEWS_FOR_INDEX_PAGE: 'GET_REVIEWS_FOR_INDEX_PAGE',

  GET_CONTENT_FOR_INDEX_PAGE: 'GET_CONTENT_FOR_INDEX_PAGE',

  START_TO_GET_INDEX_PAGE_CONTENT: 'START_TO_GET_INDEX_PAGE_CONTENT',

  ERROR_TO_GET_INDEX_PAGE_CONTENT: 'ERROR_TO_GET_INDEX_PAGE_CONTENT',

}

export default types
